### ISSUE TITLE
未安装微博客户端不能分享图片？

### ISSUE THREAD

**Issue by kingsword** [xumeng/XMShareModule#2]
看到代码这样写的，当判断没有安装微博客户端的时候，不设置mediaObject，是因为微博的限制，在未安装客户端时只能发文字么？
- (WBMessageObject *)messageToShare
  {
  
  WBMessageObject *message = [WBMessageObject message];
  BOOL hadInstalledWeibo = [[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:@"weibo://"]];
  
  if(hadInstalledWeibo){
      WBWebpageObject *webpage = [WBWebpageObject object];
      webpage.objectID = @"identifier1";
      webpage.title = self.shareTitle;
      webpage.description = self.shareText;
      //  可改为自定义图片
      webpage.thumbnailData = UIImageJPEGRepresentation(SHARE_IMG, SHARE_IMG_COMPRESSION_QUALITY);
      webpage.webpageUrl = self.shareUrl;
  
  ```
  message.mediaObject = webpage;
  ```
  
  }
  
  message.text = [NSString stringWithFormat:@"%@ - %@ %@", self.shareTitle, self.shareText, self.shareUrl];
  
  return message;

}

**Comment by xumeng** [comment]
是的，你可以尝试一下。

**Comment by kingsword** [comment]
@xumeng 多谢 我试过了 确实如此
