### ISSUE TITLE
缩略图问题

### ISSUE THREAD

**Issue by Easyzhan** [xumeng/XMShareModule#3]
不能超过32k，如果设置超过了点击就不能分享了，如果不用在乎这个尺寸就更好了

**Comment by Tralny** [comment]
微博分享不能将图片带出，我修改成了WBImageObject这个类解决了，再有就是现在这个版本分享的时候 URL 最后一个字段会隔离开，message.text 那里多打印了一个字符串，我这边删除就好了。

**Comment by xumeng** [comment]
可以扩展一下，前阵子有个分享图片的需求，我这边扩展了一下实现了，需要的话，最近整理一下代码更新上来。

**Comment by Tralny** [comment]
虽然我这边也实现了，但是为了后人还是更新一下吧，哈哈哈哈哈
